source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.4.7'

gem 'rails', '~> 7.1'
gem 'puma', '>= 6.0'
gem 'bootsnap', require: false

# API
gem 'rack-cors', require: 'rack/cors'

# Shopify
gem 'shopify_app'
gem 'shopify_api'

# HTTP Client
gem 'httparty'
gem 'sprockets-rails'

# Config
gem 'dotenv-rails'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'fiddle'
  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
end

group :development do
  gem 'listen'
  gem 'sqlite3', '~> 1.7'
end
